#!/usr/bin/env python3
"""Generate kernel/font8x16.h from a PSF console font.

The BIOS gave us an 8x16 font via int 10h/1130h; UEFI has no such service, so
the kernel carries its own copy.  Defaults to Terminus (SIL OFL 1.1); pass a
different .psf/.psfu (optionally gzipped) to swap it.

    tools/mkfont.py [source.psfu[.gz]] > kernel/font8x16.h
"""
import gzip
import struct
import sys

DEFAULT = "/usr/share/kbd/consolefonts/Lat2-Terminus16.psfu.gz"


def read_font(path):
    opener = gzip.open if path.endswith(".gz") else open
    d = opener(path, "rb").read()

    if d[:2] == b"\x36\x04":                      # PSF1: always 8 pixels wide
        charsize = d[3]
        return d, 4, charsize, 8, charsize
    if d[:4] == b"\x72\xb5\x4a\x86":              # PSF2
        _ver, hdr, _flags, _len, charsize, height, width = struct.unpack_from("<7I", d, 4)
        return d, hdr, charsize, width, height
    raise SystemExit("not a PSF font: %s" % path)


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT
    d, off, charsize, width, height = read_font(path)
    if width != 8 or height != 16:
        raise SystemExit("need an 8x16 font, got %dx%d" % (width, height))

    name = path.rsplit("/", 1)[-1]
    w = sys.stdout.write
    w("/* 8x16 console font, 256 glyphs, one byte per scanline (MSB = leftmost pixel).\n")
    w(" *\n")
    w(" * Generated by tools/mkfont.py from %s.\n" % name)
    w(" * UEFI provides no BIOS font, so the kernel carries its own.\n")
    w(" */\n")
    w("#pragma once\n\n")
    w("static const unsigned char font8x16[256 * 16] = {\n")
    for i in range(256):
        g = d[off + i * charsize: off + i * charsize + 16]
        g = g + b"\0" * (16 - len(g))
        label = chr(i) if 32 <= i < 127 else "."
        w("    %s,  /* %3d %s */\n" % (", ".join("0x%02X" % b for b in g), i, label))
    w("};\n")


if __name__ == "__main__":
    main()
